# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target '_BusinessAppSwift_' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # 2016.09.09: Contained 4.0.0 version at the time of update
  #pod 'Alamofire',
  #:git => 'https://github.com/Alamofire/Alamofire.git',
  #:branch => 'master'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  
  #pod 'CocoaLumberjack', '~> 3.0'
  pod 'CocoaLumberjack/Swift', '~> 3.0'
  pod 'FLEX', '~> 2.4', :configurations => ['Debug']
  #pod 'GoogleAnalytics', '~> 3.17' // http://stackoverflow.com/a/31758883/597292
  pod 'Google/Analytics'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'BSKeyboardControls', '~> 2.2'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'iVersion', '~> 1.11'
  pod 'JVFloatLabeledTextField', '~> 1.1'
  # PS: Made couple direct changes inside TWMessageBarManager, therefore be port these changes if will decide to upgrade this library:
  # 1) please note there were issues with TWMessageBarManager on iPad and we applied suggested fix directly: https://github.com/terryworona/TWMessageBarManager/issues/59  However then made pod to stick with this conrete version. However it was fixed and now it should work, because I wrote and it was merged: https://github.com/terryworona/TWMessageBarManager/commit/581a116f5759f66f191218a99d669fb4db9678c3  Therefore you can put "pod 'TWMessageBarManager', '~> 1.7'" and reinstall again which will remove unnecessary static fix
  # 2) also added icon adjustement. Search for "// Gytenis 07.05.15: icon's width and height will be adjusted according image"
  #pod 'TWMessageBarManager', '1.7.2'
  #pod 'TWMessageBarManager', '~> 1.8'
  pod 'SwiftMessageBar', '~> 3.0'
  pod 'SCLAlertView', '~> 0.7'
  pod 'KeychainAccess', '~> 3.0'
  pod 'EMCCountryPickerController', '~> 1.3'
  #pod 'iCarousel', '~> 1.8'
  #pod 'SwipeView', '~> 1.2.10'
  #pod 'OCMock', '~> 3.1'
  
  #Haven't used these yet
  pod 'SwiftyJSON', '~> 3.1'
  pod 'ObjectMapper', '~> 2.0'
  pod 'AlamofireObjectMapper', '~> 4.0'
  # Network abstraction layer
  #pod 'Moya', '~> 7.0'
  
  #Side menu
  #pod 'SideMenu', '~> 2.0'

  # Pods for _BusinessAppSwift_

  target '_BusinessAppSwift_Tests' do
    inherit! :search_paths
    # Pods for testing
    # Need to add again otherwise framework not found is shown
    pod 'Google/Analytics'
  end

  target '_BusinessAppSwift_UITests' do
    inherit! :search_paths
    # Pods for testing    
    # Need to add again otherwise framework not found is shown
    pod 'Google/Analytics'
  end

end

# Fixes “Use Legacy Swift Language Version” issue when performing pod update/install
# http://stackoverflow.com/a/38466703
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
