platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4'
pod 'JVFloatLabeledTextField', '~>0.0.5'
pod 'iVersion', '~> 1.11'
#pod 'SwipeView', '~> 1.2.10'
pod 'BSKeyboardControls', '2.2'
pod 'MBProgressHUD', '~> 0.9'
#pod 'iCarousel', '~> 1.8'
pod 'GoogleAnalytics', '~> 3.14’
#pod 'CrittercismSDK', '~> 4.3'
# PS: Made couple direct changes inside TWMessageBarManager, therefore be port these changes if will decide to upgrade this library:
# 1) please note there were issues with TWMessageBarManager on iPad and we applied suggested fix directly: https://github.com/terryworona/TWMessageBarManager/issues/59  However then made pod to stick with this conrete version. However it was fixed and now it should work, because I wrote and it was merged: https://github.com/terryworona/TWMessageBarManager/commit/581a116f5759f66f191218a99d669fb4db9678c3  Therefore you can put "pod 'TWMessageBarManager', '~> 1.7'" and reinstall again which will remove unnecessary static fix
# 2) also added icon adjustement. Search for "// Gytenis 07.05.15: icon's width and height will be adjusted according image"
pod 'TWMessageBarManager', '1.7.2'
pod 'Fabric'
pod 'Crashlytics'
#pod 'UICKeyChainStore', '~> 2.0'
#pod 'CountryPicker', '~> 1.2'
pod 'EMCCountryPickerController', '~> 1.3'
pod 'UICKeyChainStore', '~> 2.1'
pod 'MFSideMenu', '~> 0.5'
pod 'Parse', '~> 1.8'

pod 'OCMock', '~> 3.1'
pod 'CocoaLumberjack', '~> 2.0'
pod 'FLEX', '~> 2.1'